name: CI

on:
  push:
    branches:
    - develop

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '18.x'
    - run: npm install --force
    - run: |
        sed -i 's/{{FIREBASE_API_KEY}}/${{ secrets.FIREBASE_API_KEY }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_AUTH_DOMAIN}}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_AVATAR_IMG}}/${{ secrets.FIREBASE_AVATAR_IMG }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_CV_IMG}}/${{ secrets.FIREBASE_CV_IMG }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_PROJECT_ID}}/${{ secrets.FIREBASE_PROJECT_ID }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_STORAGE_BUCKET}}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_MESSAGING_SENDER_ID}}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_APP_ID}}/${{ secrets.FIREBASE_APP_ID }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_MEASUREMENT_ID}}/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g' src/environments/environment.prod.ts
    - run: npm run build -- --configuration=production
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}