name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@master

    # Configuração do Node.js
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: '18.x'

    # Instalação de dependências
    - name: Install dependencies
      run: npm install --force

    # Notificação de início da build
    - name: Notify Discord (Build Started)
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Build Bot", "content": "🚀 **Deploy iniciado!**\nAmbiente: `Production`\nTag: `${{ github.ref_name }}`"}' \
          ${{ env.DISCORD_WEBHOOK_URL }}

    # Substituir variáveis de ambiente no environment.prod.ts
    - name: Replace environment variables
      run: |
        sed -i 's/{{FIREBASE_API_KEY}}/${{ secrets.FIREBASE_API_KEY }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_AUTH_DOMAIN}}/${{ env.FIREBASE_AUTH_DOMAIN }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_AVATAR_IMG}}/${{ env.FIREBASE_AVATAR_IMG }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_CV_IMG}}/${{ env.FIREBASE_CV_IMG }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_PROJECT_ID}}/${{ env.FIREBASE_PROJECT_ID }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_STORAGE_BUCKET}}/${{ env.FIREBASE_STORAGE_BUCKET }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_MESSAGING_SENDER_ID}}/${{ env.FIREBASE_MESSAGING_SENDER_ID }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_APP_ID}}/${{ env.FIREBASE_APP_ID }}/g' src/environments/environment.prod.ts
        sed -i 's/{{FIREBASE_MEASUREMENT_ID}}/${{ env.FIREBASE_MEASUREMENT_ID }}/g' src/environments/environment.prod.ts

    # Build do projeto
    - name: Build Angular App
      run: npm run build -- --configuration=production

    # Deploy para Firebase Hosting
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    # Notificação de sucesso ou falha
    - name: Notify Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Build Bot", "content": "✅ **Deploy concluído com sucesso!**\nAmbiente: `Production`\nTag: `${{ github.ref_name }}`"}' \
          ${{ env.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Build Bot", "content": "❌ **Deploy falhou!**\nAmbiente: `Production`\nTag: `${{ github.ref_name }}`"}' \
          ${{ env.DISCORD_WEBHOOK_URL }}